name: Package

on:
  push:
    branches:
      - master

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io/arugal/aliyunddns
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Packages
        run: |
          docker build -t ghcr.io/arugal/aliyunddns/app:latest .
          docker push ghcr.io/arugal/aliyunddns/app:latest